{{- if .Values.cloudflared.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: 2
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: {{ .Values.cloudflared.cloudflaredImage }}:{{ .Values.cloudflared.cloudflaredVersion }}
        args:
        - tunnel
        - --config
        - /etc/cloudflared/config/config.yaml
        - run
        livenessProbe:
          httpGet:
            path: /ready
            port: 2000
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: config
          mountPath: /etc/cloudflared/config
          readOnly: true
        - name: creds
          mountPath: /etc/cloudflared/creds
          readOnly: true
      volumes:
      - name: creds
        secret:
          secretName: tunnel-credentials
      - name: config
        configMap:
          name: cloudflared
          items:
          - key: config.yaml
            path: config.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
data:
  config.yaml: |
    tunnel: flagr
    credentials-file: /etc/cloudflared/creds/{{ .Values.cloudflared.tunnelId }}.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    - hostname: {{ .Values.cloudflared.ingressHostname }}
      service: http://flagr-web:{{ .Values.service.port }}
    - service: http_status:418
{{- end }}
