{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    "helm.sh/hook-weight": "1"
    "helm.sh/hook": pre-install,pre-upgrade
  name: flagr
  namespace: {{ $.Release.Namespace }}
spec:
  refreshInterval: {{ default "1m" .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef }}
    kind: {{ .Values.externalSecrets.secretStoreKind }}
  target:
    name: flagr
    creationPolicy: Owner
  data:
  {{- range $secretKey, $secretVals := .Values.externalSecrets.secrets }}
  - secretKey: {{ $secretKey }}
    remoteRef:
      key: {{ $secretVals.secretName }}
      property: {{ $secretVals.property }}
  {{- end }}
---
{{- end }}
