externalSecrets:
  enabled: true
  refreshInterval: 1m
  secretStoreRef: production-cluster-secret-store
  secretStoreKind: ClusterSecretStore
  secrets:
    FLAGR_DB_PASSWORD:
      secretName: ssm-secret-name
      property: password
